(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Axiom show : forall {a : Set}, a -> string.

Axiom recursive : forall {a : Set}, a -> string.
