(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.
Unset Guard Checking.
Unset Positivity Checking.

(* ConfigurationSuffix *)
Definition value : int := 1.
