(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Parameter t : Set.

Parameter foo : t.

Parameter arg : forall (a b : Set), Set.

Parameter x_value : forall {a b : Set}, a -> b -> arg a b.

Module M.
  Inductive l (a : Set) : Set :=
  | Nil : l a
  | Cons : a -> l a -> l a.
  
  Arguments Nil {_}.
  Arguments Cons {_}.
  
  Parameter b_value : bool.
End M.
