(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module M.
  Definition b_value : bool := false.
  
  Definition n_value : int := 12.
End M.

Definition n_value : int := Z.add M.n_value 2.
