(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module T.
  Record signature {t : Set} : Set := {
    t := t;
    to_string : t -> string;
  }.
End T.
Definition T := @T.signature.
Arguments T {_}.

Module M.
  Definition t : Set := int.
  
  Definition to_string : int -> string := RocqOfOCaml.Stdlib.string_of_int.
End M.

Definition int_to_string : int -> string := M.to_string.
