(** File generated by rocq-of-ocaml *)
Require Import RocqOfOCaml.RocqOfOCaml.
Require Import RocqOfOCaml.Settings.

Module Included.
  Record signature {item : Set} : Set := {
    item := item;
    item_value : item;
  }.
End Included.
Definition Included := @Included.signature.
Arguments Included {_}.

Parameter Included_Included_item : Set.

Parameter Included_Included : Included (item := Included_Included_item).

Definition item := Included_Included.(Included.item).

Definition item_value : item := Included_Included.(Included.item_value).

Parameter inline_type : Set.

Parameter inline_value : inline_type.

Module point.
  Record record : Set := Build {
    x : int;
    move : int -> int;
  }.
End point.
Definition point := point.record.

Module M.
  Parameter t : Set.
  
  Parameter v_value : t.
End M.

Module Alias := M.

Module NestedSig.
  Record signature : Set := {
    nested_sig_value : int;
  }.
End NestedSig.
Definition NestedSig := NestedSig.signature.

Module FromTypeof.
  Parameter t : Set.
  
  Parameter v_value : t.
End FromTypeof.

Module Arg.
  Record signature {t : Set} : Set := {
    t := t;
    v_value : t;
  }.
End Arg.
Definition Arg := @Arg.signature.
Arguments Arg {_}.

Module Result.
  Record signature {result : Set} : Set := {
    result := result;
    result_value : int -> result;
  }.
End Result.
Definition Result := @Result.signature.
Arguments Result {_}.

Parameter Functor_result : forall {X_t : Set} (X : Arg (t := X_t)), Set.

Parameter Functor :
  forall {X_t : Set},
  forall (X : Arg (t := X_t)), Result (result := Functor_result X).
