name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5.4.1
        rocq-version:
          - 9.0.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # for the code coverage tool

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam repo add rocq-released https://rocq-prover.org/opam/released
      - run: opam install rocq-prover=${{ matrix.rocq-version }}
      - run: opam pin add coq-of-ocaml.dev . --no-action
      - run: opam depext conf-ruby --yes
      - run: opam install coq-of-ocaml --deps-only --with-test
      - run: opam install coq-of-ocaml --verbose
      - run: opam exec -- make test
